// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// aux_cube_expm
arma::cube aux_cube_expm(arma::cube& data3d);
RcppExport SEXP _RiemannSPD_aux_cube_expm(SEXP data3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type data3d(data3dSEXP);
    rcpp_result_gen = Rcpp::wrap(aux_cube_expm(data3d));
    return rcpp_result_gen;
END_RCPP
}
// aux_cube_logm
arma::cube aux_cube_logm(arma::cube& data3d);
RcppExport SEXP _RiemannSPD_aux_cube_logm(SEXP data3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type data3d(data3dSEXP);
    rcpp_result_gen = Rcpp::wrap(aux_cube_logm(data3d));
    return rcpp_result_gen;
END_RCPP
}
// aux_halfinv
arma::mat aux_halfinv(arma::mat& X);
RcppExport SEXP _RiemannSPD_aux_halfinv(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(aux_halfinv(X));
    return rcpp_result_gen;
END_RCPP
}
// aux_3d_mean
arma::mat aux_3d_mean(arma::cube& data3d);
RcppExport SEXP _RiemannSPD_aux_3d_mean(SEXP data3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type data3d(data3dSEXP);
    rcpp_result_gen = Rcpp::wrap(aux_3d_mean(data3d));
    return rcpp_result_gen;
END_RCPP
}
// aux_3d_transport
arma::cube aux_3d_transport(arma::mat& pt_start, arma::mat& pt_end, arma::cube& data3d);
RcppExport SEXP _RiemannSPD_aux_3d_transport(SEXP pt_startSEXP, SEXP pt_endSEXP, SEXP data3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type pt_start(pt_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type pt_end(pt_endSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type data3d(data3dSEXP);
    rcpp_result_gen = Rcpp::wrap(aux_3d_transport(pt_start, pt_end, data3d));
    return rcpp_result_gen;
END_RCPP
}
// aux_expm
arma::mat aux_expm(arma::mat& X);
RcppExport SEXP _RiemannSPD_aux_expm(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(aux_expm(X));
    return rcpp_result_gen;
END_RCPP
}
// aux_3d_tan2mani
arma::cube aux_3d_tan2mani(arma::mat& Cref, arma::cube& tan3d);
RcppExport SEXP _RiemannSPD_aux_3d_tan2mani(SEXP CrefSEXP, SEXP tan3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Cref(CrefSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type tan3d(tan3dSEXP);
    rcpp_result_gen = Rcpp::wrap(aux_3d_tan2mani(Cref, tan3d));
    return rcpp_result_gen;
END_RCPP
}
// aux_3d_mani2tan
arma::cube aux_3d_mani2tan(arma::mat& Cref, arma::cube& data3d);
RcppExport SEXP _RiemannSPD_aux_3d_mani2tan(SEXP CrefSEXP, SEXP data3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Cref(CrefSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type data3d(data3dSEXP);
    rcpp_result_gen = Rcpp::wrap(aux_3d_mani2tan(Cref, data3d));
    return rcpp_result_gen;
END_RCPP
}
// cpp_representation_cmds
Rcpp::List cpp_representation_cmds(arma::mat& pdist, int ndim);
RcppExport SEXP _RiemannSPD_cpp_representation_cmds(SEXP pdistSEXP, SEXP ndimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type pdist(pdistSEXP);
    Rcpp::traits::input_parameter< int >::type ndim(ndimSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_representation_cmds(pdist, ndim));
    return rcpp_result_gen;
END_RCPP
}
// selector_mean
Rcpp::List selector_mean(arma::cube& data, arma::vec& weight, int maxiter, double abstol, std::string geom);
RcppExport SEXP _RiemannSPD_selector_mean(SEXP dataSEXP, SEXP weightSEXP, SEXP maxiterSEXP, SEXP abstolSEXP, SEXP geomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< std::string >::type geom(geomSEXP);
    rcpp_result_gen = Rcpp::wrap(selector_mean(data, weight, maxiter, abstol, geom));
    return rcpp_result_gen;
END_RCPP
}
// selector_median
Rcpp::List selector_median(arma::cube& data, arma::vec& weight, int maxiter, double abstol, std::string geom);
RcppExport SEXP _RiemannSPD_selector_median(SEXP dataSEXP, SEXP weightSEXP, SEXP maxiterSEXP, SEXP abstolSEXP, SEXP geomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< std::string >::type geom(geomSEXP);
    rcpp_result_gen = Rcpp::wrap(selector_median(data, weight, maxiter, abstol, geom));
    return rcpp_result_gen;
END_RCPP
}
// src_pdist
arma::mat src_pdist(arma::cube& data, std::string geometry);
RcppExport SEXP _RiemannSPD_src_pdist(SEXP dataSEXP, SEXP geometrySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type geometry(geometrySEXP);
    rcpp_result_gen = Rcpp::wrap(src_pdist(data, geometry));
    return rcpp_result_gen;
END_RCPP
}
// src_pdist2
arma::mat src_pdist2(arma::cube& data1, arma::cube& data2, std::string geometry);
RcppExport SEXP _RiemannSPD_src_pdist2(SEXP data1SEXP, SEXP data2SEXP, SEXP geometrySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type data1(data1SEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type data2(data2SEXP);
    Rcpp::traits::input_parameter< std::string >::type geometry(geometrySEXP);
    rcpp_result_gen = Rcpp::wrap(src_pdist2(data1, data2, geometry));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RiemannSPD_aux_cube_expm", (DL_FUNC) &_RiemannSPD_aux_cube_expm, 1},
    {"_RiemannSPD_aux_cube_logm", (DL_FUNC) &_RiemannSPD_aux_cube_logm, 1},
    {"_RiemannSPD_aux_halfinv", (DL_FUNC) &_RiemannSPD_aux_halfinv, 1},
    {"_RiemannSPD_aux_3d_mean", (DL_FUNC) &_RiemannSPD_aux_3d_mean, 1},
    {"_RiemannSPD_aux_3d_transport", (DL_FUNC) &_RiemannSPD_aux_3d_transport, 3},
    {"_RiemannSPD_aux_expm", (DL_FUNC) &_RiemannSPD_aux_expm, 1},
    {"_RiemannSPD_aux_3d_tan2mani", (DL_FUNC) &_RiemannSPD_aux_3d_tan2mani, 2},
    {"_RiemannSPD_aux_3d_mani2tan", (DL_FUNC) &_RiemannSPD_aux_3d_mani2tan, 2},
    {"_RiemannSPD_cpp_representation_cmds", (DL_FUNC) &_RiemannSPD_cpp_representation_cmds, 2},
    {"_RiemannSPD_selector_mean", (DL_FUNC) &_RiemannSPD_selector_mean, 5},
    {"_RiemannSPD_selector_median", (DL_FUNC) &_RiemannSPD_selector_median, 5},
    {"_RiemannSPD_src_pdist", (DL_FUNC) &_RiemannSPD_src_pdist, 2},
    {"_RiemannSPD_src_pdist2", (DL_FUNC) &_RiemannSPD_src_pdist2, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_RiemannSPD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
