// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// aux_cube_logm
arma::cube aux_cube_logm(arma::cube& data3d);
RcppExport SEXP _RiemannSPD_aux_cube_logm(SEXP data3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type data3d(data3dSEXP);
    rcpp_result_gen = Rcpp::wrap(aux_cube_logm(data3d));
    return rcpp_result_gen;
END_RCPP
}
// aux_cube_expm
arma::cube aux_cube_expm(arma::cube& data3d);
RcppExport SEXP _RiemannSPD_aux_cube_expm(SEXP data3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type data3d(data3dSEXP);
    rcpp_result_gen = Rcpp::wrap(aux_cube_expm(data3d));
    return rcpp_result_gen;
END_RCPP
}
// cpp_swdist_projection
arma::mat cpp_swdist_projection(arma::cube& LogX, arma::cube& LogY);
RcppExport SEXP _RiemannSPD_cpp_swdist_projection(SEXP LogXSEXP, SEXP LogYSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type LogX(LogXSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type LogY(LogYSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_swdist_projection(LogX, LogY));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RiemannSPD_aux_cube_logm", (DL_FUNC) &_RiemannSPD_aux_cube_logm, 1},
    {"_RiemannSPD_aux_cube_expm", (DL_FUNC) &_RiemannSPD_aux_cube_expm, 1},
    {"_RiemannSPD_cpp_swdist_projection", (DL_FUNC) &_RiemannSPD_cpp_swdist_projection, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RiemannSPD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
