// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// aux_halfinv
arma::mat aux_halfinv(arma::mat& X);
RcppExport SEXP _RiemannSPD_aux_halfinv(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(aux_halfinv(X));
    return rcpp_result_gen;
END_RCPP
}
// selector_mean
Rcpp::List selector_mean(arma::cube& data, arma::vec& weight, int maxiter, double abstol, std::string geom);
RcppExport SEXP _RiemannSPD_selector_mean(SEXP dataSEXP, SEXP weightSEXP, SEXP maxiterSEXP, SEXP abstolSEXP, SEXP geomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< std::string >::type geom(geomSEXP);
    rcpp_result_gen = Rcpp::wrap(selector_mean(data, weight, maxiter, abstol, geom));
    return rcpp_result_gen;
END_RCPP
}
// src_pdist
arma::mat src_pdist(arma::cube& data, std::string geometry);
RcppExport SEXP _RiemannSPD_src_pdist(SEXP dataSEXP, SEXP geometrySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type geometry(geometrySEXP);
    rcpp_result_gen = Rcpp::wrap(src_pdist(data, geometry));
    return rcpp_result_gen;
END_RCPP
}
// src_pdist2
arma::mat src_pdist2(arma::cube& data1, arma::cube& data2, std::string geometry);
RcppExport SEXP _RiemannSPD_src_pdist2(SEXP data1SEXP, SEXP data2SEXP, SEXP geometrySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type data1(data1SEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type data2(data2SEXP);
    Rcpp::traits::input_parameter< std::string >::type geometry(geometrySEXP);
    rcpp_result_gen = Rcpp::wrap(src_pdist2(data1, data2, geometry));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RiemannSPD_aux_halfinv", (DL_FUNC) &_RiemannSPD_aux_halfinv, 1},
    {"_RiemannSPD_selector_mean", (DL_FUNC) &_RiemannSPD_selector_mean, 5},
    {"_RiemannSPD_src_pdist", (DL_FUNC) &_RiemannSPD_src_pdist, 2},
    {"_RiemannSPD_src_pdist2", (DL_FUNC) &_RiemannSPD_src_pdist2, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_RiemannSPD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
