# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aux_halfinv <- function(X) {
    .Call('_RiemannSPD_aux_halfinv', PACKAGE = 'RiemannSPD', X)
}

selector_mean <- function(data, weight, maxiter, abstol, geom) {
    .Call('_RiemannSPD_selector_mean', PACKAGE = 'RiemannSPD', data, weight, maxiter, abstol, geom)
}

src_pdist <- function(data, geometry) {
    .Call('_RiemannSPD_src_pdist', PACKAGE = 'RiemannSPD', data, geometry)
}

src_pdist2 <- function(data1, data2, geometry) {
    .Call('_RiemannSPD_src_pdist2', PACKAGE = 'RiemannSPD', data1, data2, geometry)
}

