# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aux_cube_logm <- function(data3d) {
    .Call(`_RiemannSPD_aux_cube_logm`, data3d)
}

aux_cube_expm <- function(data3d) {
    .Call(`_RiemannSPD_aux_cube_expm`, data3d)
}

cpp_swdist_projection <- function(LogX, LogY) {
    .Call(`_RiemannSPD_cpp_swdist_projection`, LogX, LogY)
}

