# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aux_cube_expm <- function(data3d) {
    .Call('_RiemannSPD_aux_cube_expm', PACKAGE = 'RiemannSPD', data3d)
}

aux_cube_logm <- function(data3d) {
    .Call('_RiemannSPD_aux_cube_logm', PACKAGE = 'RiemannSPD', data3d)
}

aux_halfinv <- function(X) {
    .Call('_RiemannSPD_aux_halfinv', PACKAGE = 'RiemannSPD', X)
}

aux_3d_mean <- function(data3d) {
    .Call('_RiemannSPD_aux_3d_mean', PACKAGE = 'RiemannSPD', data3d)
}

aux_3d_transport <- function(pt_start, pt_end, data3d) {
    .Call('_RiemannSPD_aux_3d_transport', PACKAGE = 'RiemannSPD', pt_start, pt_end, data3d)
}

aux_expm <- function(X) {
    .Call('_RiemannSPD_aux_expm', PACKAGE = 'RiemannSPD', X)
}

aux_3d_tan2mani <- function(Cref, tan3d) {
    .Call('_RiemannSPD_aux_3d_tan2mani', PACKAGE = 'RiemannSPD', Cref, tan3d)
}

aux_3d_mani2tan <- function(Cref, data3d) {
    .Call('_RiemannSPD_aux_3d_mani2tan', PACKAGE = 'RiemannSPD', Cref, data3d)
}

cpp_representation_cmds <- function(pdist, ndim) {
    .Call('_RiemannSPD_cpp_representation_cmds', PACKAGE = 'RiemannSPD', pdist, ndim)
}

selector_mean <- function(data, weight, maxiter, abstol, geom) {
    .Call('_RiemannSPD_selector_mean', PACKAGE = 'RiemannSPD', data, weight, maxiter, abstol, geom)
}

selector_median <- function(data, weight, maxiter, abstol, geom) {
    .Call('_RiemannSPD_selector_median', PACKAGE = 'RiemannSPD', data, weight, maxiter, abstol, geom)
}

src_pdist <- function(data, geometry) {
    .Call('_RiemannSPD_src_pdist', PACKAGE = 'RiemannSPD', data, geometry)
}

src_pdist2 <- function(data1, data2, geometry) {
    .Call('_RiemannSPD_src_pdist2', PACKAGE = 'RiemannSPD', data1, data2, geometry)
}

